// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxz6CnmOuI0oT2icHaFBBG2DqG8HE-_yw',
    appId: '1:791715107390:web:9b701d9eec46522ccef76f',
    messagingSenderId: '791715107390',
    projectId: 'rslbanglaapps',
    authDomain: 'rslbanglaapps.firebaseapp.com',
    storageBucket: 'rslbanglaapps.appspot.com',
    measurementId: 'G-HQVF1CL201',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3U8Yuc1Ffm6-IK592Ft2H5L84M2EL2B4',
    appId: '1:791715107390:android:e9e00c13d01bd07ecef76f',
    messagingSenderId: '791715107390',
    projectId: 'rslbanglaapps',
    storageBucket: 'rslbanglaapps.appspot.com',
  );
}
